# Generated by Django 6.1.1 on 2026-09-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(choices=[('cubo', '🧩 Cubo'), ('rayo', '⚡ Rayo'), ('cohete', '🚀 Cohete'), ('estrella', '⭐ Estrella')], default='cubo', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', 'Prefiero no indicarlo'), ('f', 'Femenino'), ('m', 'Masculino'), ('otro', 'Otro')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ExperienciaCubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('3x3', '3×3×3'), ('4x4', '4×4×4'), ('5x5', '5×5×5'), ('6x6', '6×6×6'), ('mirror', 'Mirror'), ('megaminx', 'Megaminx'), ('pyraminx', 'Pyraminx')], max_length=20)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_cubos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tipo'), name='core_xp_usuario_tipo_unico')],
            },
        ),
    ]
