# Generated by Django 6.1.1 on 2026-09-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil_avatar_perfil_sexo_experienciacubo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciacubo',
            name='resto_practica_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SesionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tipo', models.CharField(choices=[('3x3', '3×3×3'), ('4x4', '4×4×4'), ('5x5', '5×5×5'), ('6x6', '6×6×6'), ('mirror', 'Mirror'), ('megaminx', 'Megaminx'), ('pyraminx', 'Pyraminx')], max_length=20)),
                ('ultimo_pulso', models.DateTimeField()),
                ('secuencia', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_practica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
