# Generated by Django 6.1.1 on 2026-09-28 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_suscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPremium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField(default=2000)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('vendedor_id', models.CharField(max_length=40)),
                ('produccion', models.BooleanField(default=False)),
                ('preferencia_id', models.CharField(blank=True, max_length=200)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('pago_externo_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(default='creado', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.DateTimeField(blank=True, null=True)),
                ('actualizado_mp', models.DateTimeField(blank=True, null=True)),
                ('acceso_inicio', models.DateTimeField(blank=True, null=True)),
                ('acceso_fin', models.DateTimeField(blank=True, null=True)),
                ('dia_ancla', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aplicado', models.BooleanField(default=False)),
                ('acceso_revocado', models.BooleanField(default=False)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_premium', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
