# Generated by Django 6.1.1 on 2026-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagopremium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopremium',
            name='monto',
            field=models.PositiveIntegerField(default=1990),
        ),
    ]
