# Generated by Django 6.1.1 on 2026-09-30 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pagopremium_monto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacionClave',
            fields=[
                ('clave', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('codigo_hash', models.CharField(blank=True, default='', max_length=64)),
                ('password_hash', models.CharField(blank=True, default='', max_length=64)),
                ('expira', models.DateTimeField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('consumido', models.BooleanField(default=False)),
                ('ventana', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('envios', models.PositiveIntegerField(default=0)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
